name: tavern
description: An open-source pub.dev client for searching and subscribing to packages
authors:
  - Jonathan White <jwhite@thinkdigital.software>
  - GroovinChip <groovinchip@gmail.com>
version: 0.9.5

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  webfeed: ^0.4.2
  bloc: ^0.14.4
  flutter_bloc: ^0.20.1
  hydrated_bloc: ^0.3.2
  groovin_material_icons: ^1.1.6
  pub_client:
    git: https://github.com/ThinkDigitalSoftware/pub_client.git
  flutter_markdown: ^0.2.0
  html2md: ^0.3.2
  material_segmented_control: ^2.0.3
  cupertino_icons: ^0.1.2
  groovin_widgets: ^1.4.2
  provider: ^3.0.0+1
  url_launcher: ^5.1.2
  dynamic_theme: ^1.0.1
  package_info: ^0.4.0+6
  rounded_modal: ^1.0.1
  back_button_interceptor: ^4.0.7
  shared_preferences: ^0.5.3+4
  flutter_pagewise:

dev_dependencies:

  pedantic: ^1.8.0+1


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - images/

  fonts:
    - family: Metropolis
      fonts:
        - asset: fonts/Metropolis-Regular.otf

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
